# Generated by Django 5.0.7 on 2025-06-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('complaint_text', models.TextField()),
                ('sentiment', models.CharField(default='none', max_length=100)),
                ('image_classification', models.CharField(default='none', max_length=100)),
                ('pnr_number', models.CharField(default='UNKNOWN', max_length=50)),
                ('complaint_image', models.ImageField(blank=True, default='Not Classified', null=True, upload_to='complaint_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
